import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Saludo from './components/Saludo.js'
import Audio from './components/Audio.js'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Saludo texto="Ale" edad="20" video="https://www.w3schools.com/tags/movie.mp4">
          <button>Esto es un boton</button>
          <span></span>
          <Audio audio="https://open.spotify.com/track/259Zco2M4NlQ5lTXuq20AI?si=212a9a4ad7ce4995"></Audio>
        </Saludo>
      </main>
    </>
  )
}
